/**
 * Danh sách các hãng xe phổ biến tại Việt Nam
 */
export const VEHICLE_BRANDS: { label: string; value: string }[] = [
  { label: "Honda", value: "Honda" },
  { label: "Yamaha", value: "Yamaha" },
  { label: "Piaggio", value: "Piaggio" },
  { label: "SYM", value: "SYM" },
  { label: "Vespa", value: "Vespa" },
  { label: "Kymco", value: "Kymco" },
  { label: "Pega", value: "Pega" },
  { label: "Suzuki", value: "Suzuki" },
  { label: "Ducati", value: "Ducati" },
  { label: "Kawasaki", value: "Kawasaki" },
  { label: "Benelli", value: "Benelli" },
  { label: "Harley-Davidson", value: "Harley-Davidson" },
  { label: "BMW", value: "BMW" },
  { label: "Triumph", value: "Triumph" },
  { label: "Khác", value: "Khác" },
];

/**
 * Mapping các dòng xe theo từng hãng
 */
export const VEHICLE_MODELS_BY_BRAND: Record<
  string,
  { label: string; value: string }[]
> = {
  Honda: [
    { label: "SH", value: "SH" },
    { label: "SH Mode", value: "SH Mode" },
    { label: "SH 150i", value: "SH 150i" },
    { label: "SH 350i", value: "SH 350i" },
    { label: "Lead", value: "Lead" },
    { label: "Air Blade", value: "Air Blade" },
    { label: "Air Blade 125", value: "Air Blade 125" },
    { label: "Air Blade 150", value: "Air Blade 150" },
    { label: "PCX", value: "PCX" },
    { label: "PCX 150", value: "PCX 150" },
    { label: "PCX 160", value: "PCX 160" },
    { label: "Vision", value: "Vision" },
    { label: "Click", value: "Click" },
    { label: "Click 125i", value: "Click 125i" },
    { label: "Click 150i", value: "Click 150i" },
    { label: "Future", value: "Future" },
    { label: "Future 125i", value: "Future 125i" },
    { label: "Future 125 Fi", value: "Future 125 Fi" },
    { label: "Wave", value: "Wave" },
    { label: "Wave RSX", value: "Wave RSX" },
    { label: "Wave Alpha", value: "Wave Alpha" },
    { label: "Blade", value: "Blade" },
    { label: "Winner", value: "Winner" },
    { label: "Winner X", value: "Winner X" },
    { label: "CBR", value: "CBR" },
    { label: "CBR150R", value: "CBR150R" },
    { label: "CBR250R", value: "CBR250R" },
    { label: "CB", value: "CB" },
    { label: "CB150R", value: "CB150R" },
    { label: "CRF", value: "CRF" },
    { label: "CRF150L", value: "CRF150L" },
    { label: "CRF250L", value: "CRF250L" },
    { label: "Rebel", value: "Rebel" },
    { label: "X-ADV", value: "X-ADV" },
  ],
  Yamaha: [
    { label: "Exciter", value: "Exciter" },
    { label: "Exciter 150", value: "Exciter 150" },
    { label: "Exciter 155", value: "Exciter 155" },
    { label: "Grande", value: "Grande" },
    { label: "Grande 125", value: "Grande 125" },
    { label: "Janus", value: "Janus" },
    { label: "Jupiter", value: "Jupiter" },
    { label: "Jupiter FI", value: "Jupiter FI" },
    { label: "Jupiter RC", value: "Jupiter RC" },
    { label: "Latte", value: "Latte" },
    { label: "Nouvo", value: "Nouvo" },
    { label: "NVX", value: "NVX" },
    { label: "NVX 155", value: "NVX 155" },
    { label: "Sirius", value: "Sirius" },
    { label: "Sirius RC", value: "Sirius RC" },
    { label: "Yamaha YZF-R15", value: "YZF-R15" },
    { label: "Yamaha MT", value: "MT" },
    { label: "Yamaha MT-07", value: "MT-07" },
    { label: "Yamaha MT-09", value: "MT-09" },
    { label: "FreeGo", value: "FreeGo" },
    { label: "Fino", value: "Fino" },
    { label: "Fazzio", value: "Fazzio" },
    { label: "Mio", value: "Mio" },
    { label: "Mio Sporty", value: "Mio Sporty" },
  ],
  Piaggio: [
    { label: "Medley", value: "Medley" },
    { label: "Medley 125", value: "Medley 125" },
    { label: "Medley 150", value: "Medley 150" },
    { label: "Liberty", value: "Liberty" },
    { label: "Liberty 125", value: "Liberty 125" },
    { label: "Liberty 150", value: "Liberty 150" },
    { label: "Vespa S", value: "Vespa S" },
    { label: "Vespa GTS", value: "Vespa GTS" },
    { label: "Vespa Primavera", value: "Vespa Primavera" },
    { label: "Vespa Sprint", value: "Vespa Sprint" },
    { label: "Beverly", value: "Beverly" },
    { label: "Fly", value: "Fly" },
  ],
  SYM: [
    { label: "Attila", value: "Attila" },
    { label: "Attila Elizabeth", value: "Attila Elizabeth" },
    { label: "Galaxy", value: "Galaxy" },
    { label: "Galaxy 125", value: "Galaxy 125" },
    { label: "Joyride", value: "Joyride" },
    { label: "Joyride 200i", value: "Joyride 200i" },
    { label: "Symbike", value: "Symbike" },
    { label: "Wolf", value: "Wolf" },
    { label: "Vega", value: "Vega" },
  ],
  Vespa: [
    { label: "Vespa LX", value: "Vespa LX" },
    { label: "Vespa GTS", value: "Vespa GTS" },
    { label: "Vespa GTS Super", value: "Vespa GTS Super" },
    { label: "Vespa Sprint", value: "Vespa Sprint" },
    { label: "Vespa Primavera", value: "Vespa Primavera" },
    { label: "Vespa S", value: "Vespa S" },
    { label: "Vespa 946", value: "Vespa 946" },
    { label: "Vespa Sei Giorni", value: "Vespa Sei Giorni" },
  ],
  Kymco: [
    { label: "Like", value: "Like" },
    { label: "Like 125", value: "Like 125" },
    { label: "Like 200i", value: "Like 200i" },
    { label: "Agility", value: "Agility" },
    { label: "Agility 125", value: "Agility 125" },
    { label: "Agility 150", value: "Agility 150" },
    { label: "People", value: "People" },
    { label: "Downtown", value: "Downtown" },
  ],
  Pega: [
    { label: "Pega S", value: "Pega S" },
    { label: "Pega G", value: "Pega G" },
    { label: "Pega Sport", value: "Pega Sport" },
    { label: "Pega Elegant", value: "Pega Elegant" },
  ],
  Suzuki: [
    { label: "Raider", value: "Raider" },
    { label: "Raider 150", value: "Raider 150" },
    { label: "Satria", value: "Satria" },
    { label: "Satria F150", value: "Satria F150" },
    { label: "Hayate", value: "Hayate" },
    { label: "Address", value: "Address" },
    { label: "GSX-R", value: "GSX-R" },
    { label: "GSX-S", value: "GSX-S" },
    { label: "SV", value: "SV" },
  ],
  Ducati: [
    { label: "Ducati Scrambler", value: "Ducati Scrambler" },
    { label: "Ducati Monster", value: "Ducati Monster" },
    { label: "Ducati Panigale", value: "Ducati Panigale" },
    { label: "Ducati Multistrada", value: "Ducati Multistrada" },
    { label: "Ducati Diavel", value: "Ducati Diavel" },
    { label: "Ducati Hypermotard", value: "Ducati Hypermotard" },
    { label: "Ducati SuperSport", value: "Ducati SuperSport" },
  ],
  Kawasaki: [
    { label: "Ninja", value: "Ninja" },
    { label: "Ninja 250", value: "Ninja 250" },
    { label: "Ninja 300", value: "Ninja 300" },
    { label: "Ninja 400", value: "Ninja 400" },
    { label: "Ninja 650", value: "Ninja 650" },
    { label: "Ninja ZX-6R", value: "Ninja ZX-6R" },
    { label: "Ninja ZX-10R", value: "Ninja ZX-10R" },
    { label: "Z", value: "Z" },
    { label: "Z250", value: "Z250" },
    { label: "Z400", value: "Z400" },
    { label: "Z650", value: "Z650" },
    { label: "Z900", value: "Z900" },
    { label: "Vulcan", value: "Vulcan" },
    { label: "Versys", value: "Versys" },
    { label: "ER-6N", value: "ER-6N" },
  ],
  Benelli: [
    { label: "Benelli TNT", value: "Benelli TNT" },
    { label: "Benelli TRK", value: "Benelli TRK" },
    { label: "Benelli Leoncino", value: "Benelli Leoncino" },
    { label: "Benelli BN", value: "Benelli BN" },
    { label: "Benelli Imperiale", value: "Benelli Imperiale" },
  ],
  "Harley-Davidson": [
    { label: "Harley Sportster", value: "Harley Sportster" },
    { label: "Harley Softail", value: "Harley Softail" },
    { label: "Harley Touring", value: "Harley Touring" },
    { label: "Harley Street", value: "Harley Street" },
  ],
  BMW: [
    { label: "BMW G310R", value: "BMW G310R" },
    { label: "BMW G310GS", value: "BMW G310GS" },
    { label: "BMW R1200GS", value: "BMW R1200GS" },
    { label: "BMW S1000RR", value: "BMW S1000RR" },
    { label: "BMW F800", value: "BMW F800" },
    { label: "BMW C650", value: "BMW C650" },
  ],
  Triumph: [
    { label: "Triumph Tiger", value: "Triumph Tiger" },
    { label: "Triumph Speed Triple", value: "Triumph Speed Triple" },
    { label: "Triumph Street Triple", value: "Triumph Street Triple" },
    { label: "Triumph Bonneville", value: "Triumph Bonneville" },
    { label: "Triumph Scrambler", value: "Triumph Scrambler" },
  ],
  Khác: [],
};

/**
 * Helper function để lấy danh sách model theo brand
 */
export function getModelsByBrand(brand: string): { label: string; value: string }[] {
  return VEHICLE_MODELS_BY_BRAND[brand] || [];
}

