const fs = require('fs');
const path = require('path');
const dotenv = require('dotenv');

// Try to load .env file (local development)
const envFile = path.resolve(__dirname, '../env');
dotenv.config({ path: envFile });

// Get API URL from process.env (Render) or .env (local) or use default
const apiUrl = process.env.API_URL || 'http://localhost:3000/api';
const nodeEnv = process.env.NODE_ENV || 'development';
const production = nodeEnv === 'production';

// Generate environment.ts content
const envContent = `// This file is auto-generated by env-loader.js
// Do not edit manually
export const environment = {
  production: ${production},
  apiUrl: '${apiUrl}',
};
`;

// Write to environment.ts
const envTsPath = path.resolve(__dirname, '../src/environments/environment.ts');
fs.writeFileSync(envTsPath, envContent, 'utf8');

console.log('✅ Environment file generated successfully');
console.log(`   API URL: ${apiUrl}`);
console.log(`   Production: ${production}`);
