export const ROUTES = {
  HEALTH: '/',
  AUTH: {
    LOGIN: '/auth/login',
    REGISTER: '/auth/register',
    VERIFY_OTP: '/auth/verify-otp',
    RESEND_OTP: '/auth/resend-otp',
    FORGOT_PASSWORD: '/auth/forgot-password',
    VERIFY_RESET_PASSWORD: '/auth/verify-reset-password',
    CHANGE_PASSWORD: '/auth/change-password',
    REFRESH: '/auth/refresh',
    LOGOUT: '/auth/logout',
  },
  USER: {
    GET_USER_INFO: '/user/get-user-info',
    UPDATE_PROFILE: '/user/update-profile',
    SUBMIT_KYC: '/user/kyc',
    GET_NOTIFICATIONS: '/user/notifications',
    GET_UNREAD_NOTIFICATION_COUNT: '/user/notifications/unread-count',
    MARK_NOTIFICATION_AS_READ: '/user/notifications/:id/read',
    MARK_ALL_NOTIFICATIONS_AS_READ: '/user/notifications/read-all',
    DELETE_NOTIFICATION: '/user/notifications/:id',
    REGISTER_DEVICE_TOKEN: '/user/device-token',
    ADD_FAVORITE: '/user/favorites/:vehicleId',
    REMOVE_FAVORITE: '/user/favorites/:vehicleId',
    GET_FAVORITES: '/user/favorites',
    CHECK_FAVORITE: '/user/favorites/:vehicleId/check',
  },
  VEHICLE: {
    CREATE: '/vehicle/create',
    LIST_MY_VEHICLES: '/vehicle/my-vehicles',
    GET_MY_VEHICLE_DETAIL: '/vehicle/my-vehicles/:id',
    UPDATE_VEHICLE: '/vehicle/my-vehicles/:id',
    UPDATE_VEHICLE_STATUS: '/vehicle/my-vehicles/:id/status',
    GET_VEHICLE_DETAIL: '/vehicle/:id',
    GET_VEHICLE_REVIEWS: '/vehicle/:id/reviews',
    SEARCH: '/vehicle/search',
    LIST_POPULAR: '/vehicle/popular',
    LIST_BY_CITY: '/vehicle/by-city',
    LIST_BY_OWNER: '/vehicle/by-owner/:ownerId',
  },
  RENTAL: {
    CREATE: '/rental/create',
    GET_MY_RENTALS: '/rental/my-rentals',
    GET_RENTAL_DETAIL: '/rental/:id',
    UPDATE_RENTAL_STATUS: '/rental/:id/status',
    UPLOAD_EVIDENCE: '/rental/:id/evidence',
    CREATE_DISPUTE: '/rental/:id/dispute',
  },
  ADMIN: {
    LIST_USERS: '/admin/users',
    LIST_KYC: '/admin/kyc',
    GET_KYC_DETAIL: '/admin/kyc/:id',
    APPROVE_KYC: '/admin/kyc/:id/approve',
    REJECT_KYC: '/admin/kyc/:id/reject',
    LIST_VEHICLES: '/admin/vehicles',
    GET_VEHICLE_DETAIL: '/admin/vehicles/:id',
    APPROVE_VEHICLE: '/admin/vehicles/:id/approve',
    REJECT_VEHICLE: '/admin/vehicles/:id/reject',
    LIST_RENTALS: '/admin/rentals',
    GET_RENTAL_DETAIL: '/admin/rentals/:id',
    STATS: '/admin/stats',
  },
  FILES: {
    UPLOAD: '/files/upload',
    UPLOAD_MULTIPLE: '/files/upload-multiple',
    LIST_MY_FILES: '/files/me',
    DELETE_FILE: '/files/:id',
  },
  CHAT: {
    GET_MY_CHATS: '/chat/my-chats',
    GET_CHAT_DETAIL: '/chat/:id',
    GET_MESSAGES: '/chat/:id/messages',
    SEND_MESSAGE: '/chat/:id/messages',
    MARK_READ: '/chat/:id/read',
    GET_UNREAD_COUNT: '/chat/unread-count',
  },
  REVIEW: {
    CREATE: '/rental/:id/review',
    GET_RENTAL_REVIEWS: '/rental/:id/reviews',
    DELETE: '/review/:id',
  },
};
