/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProtectRouteImport } from './routes/_protect'
import { Route as ProtectIndexRouteImport } from './routes/_protect/index'
import { Route as ProtectVehiclesRouteImport } from './routes/_protect/vehicles'
import { Route as ProtectUsersRouteImport } from './routes/_protect/users'
import { Route as ProtectKycRouteImport } from './routes/_protect/kyc'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectRoute = ProtectRouteImport.update({
  id: '/_protect',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectIndexRoute = ProtectIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectRoute,
} as any)
const ProtectVehiclesRoute = ProtectVehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => ProtectRoute,
} as any)
const ProtectUsersRoute = ProtectUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => ProtectRoute,
} as any)
const ProtectKycRoute = ProtectKycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => ProtectRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/kyc': typeof ProtectKycRoute
  '/users': typeof ProtectUsersRoute
  '/vehicles': typeof ProtectVehiclesRoute
  '/': typeof ProtectIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/kyc': typeof ProtectKycRoute
  '/users': typeof ProtectUsersRoute
  '/vehicles': typeof ProtectVehiclesRoute
  '/': typeof ProtectIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protect': typeof ProtectRouteWithChildren
  '/login': typeof LoginRoute
  '/_protect/kyc': typeof ProtectKycRoute
  '/_protect/users': typeof ProtectUsersRoute
  '/_protect/vehicles': typeof ProtectVehiclesRoute
  '/_protect/': typeof ProtectIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/login' | '/kyc' | '/users' | '/vehicles' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/kyc' | '/users' | '/vehicles' | '/'
  id:
    | '__root__'
    | '/_protect'
    | '/login'
    | '/_protect/kyc'
    | '/_protect/users'
    | '/_protect/vehicles'
    | '/_protect/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectRoute: typeof ProtectRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protect': {
      id: '/_protect'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protect/': {
      id: '/_protect/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectIndexRouteImport
      parentRoute: typeof ProtectRoute
    }
    '/_protect/vehicles': {
      id: '/_protect/vehicles'
      path: '/vehicles'
      fullPath: '/vehicles'
      preLoaderRoute: typeof ProtectVehiclesRouteImport
      parentRoute: typeof ProtectRoute
    }
    '/_protect/users': {
      id: '/_protect/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof ProtectUsersRouteImport
      parentRoute: typeof ProtectRoute
    }
    '/_protect/kyc': {
      id: '/_protect/kyc'
      path: '/kyc'
      fullPath: '/kyc'
      preLoaderRoute: typeof ProtectKycRouteImport
      parentRoute: typeof ProtectRoute
    }
  }
}

interface ProtectRouteChildren {
  ProtectKycRoute: typeof ProtectKycRoute
  ProtectUsersRoute: typeof ProtectUsersRoute
  ProtectVehiclesRoute: typeof ProtectVehiclesRoute
  ProtectIndexRoute: typeof ProtectIndexRoute
}

const ProtectRouteChildren: ProtectRouteChildren = {
  ProtectKycRoute: ProtectKycRoute,
  ProtectUsersRoute: ProtectUsersRoute,
  ProtectVehiclesRoute: ProtectVehiclesRoute,
  ProtectIndexRoute: ProtectIndexRoute,
}

const ProtectRouteWithChildren =
  ProtectRoute._addFileChildren(ProtectRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ProtectRoute: ProtectRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
