/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminProtectRouteImport } from './routes/admin/_protect'
import { Route as AdminProtectIndexRouteImport } from './routes/admin/_protect/index'
import { Route as AdminProtectKycRouteImport } from './routes/admin/_protect/kyc'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProtectRoute = AdminProtectRouteImport.update({
  id: '/_protect',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProtectIndexRoute = AdminProtectIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminProtectRoute,
} as any)
const AdminProtectKycRoute = AdminProtectKycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => AdminProtectRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminProtectRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/kyc': typeof AdminProtectKycRoute
  '/admin/': typeof AdminProtectIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/kyc': typeof AdminProtectKycRoute
  '/admin': typeof AdminProtectIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/_protect': typeof AdminProtectRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/_protect/kyc': typeof AdminProtectKycRoute
  '/admin/_protect/': typeof AdminProtectIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin' | '/admin/login' | '/admin/kyc' | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin/login' | '/admin/kyc' | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin/_protect'
    | '/admin/login'
    | '/admin/_protect/kyc'
    | '/admin/_protect/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/_protect': {
      id: '/admin/_protect'
      path: ''
      fullPath: '/admin'
      preLoaderRoute: typeof AdminProtectRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/_protect/': {
      id: '/admin/_protect/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminProtectIndexRouteImport
      parentRoute: typeof AdminProtectRoute
    }
    '/admin/_protect/kyc': {
      id: '/admin/_protect/kyc'
      path: '/kyc'
      fullPath: '/admin/kyc'
      preLoaderRoute: typeof AdminProtectKycRouteImport
      parentRoute: typeof AdminProtectRoute
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
