const API_ENDPOINTS = {
  HEALTH: '/',
  AUTH: {
    LOGIN: '/auth/login',
    REGISTER: '/auth/register',
    VERIFY_OTP: '/auth/verify-otp',
    RESEND_OTP: '/auth/resend-otp',
    FORGOT_PASSWORD: '/auth/forgot-password',
    VERIFY_RESET_PASSWORD: '/auth/verify-reset-password',
    CHANGE_PASSWORD: '/auth/change-password',
    REFRESH: '/auth/refresh',
  },
  USER: {
    GET_USER_INFO: '/user/get-user-info',
    UPDATE_PROFILE: '/user/update-profile',
    SUBMIT_KYC: '/user/kyc',
    GET_NOTIFICATIONS: '/user/notifications',
    GET_UNREAD_NOTIFICATION_COUNT: '/user/notifications/unread-count',
    MARK_NOTIFICATION_AS_READ: (id: string) => `/user/notifications/${id}/read`,
    MARK_ALL_NOTIFICATIONS_AS_READ: '/user/notifications/read-all',
  },
  ADMIN: {
    LIST_USERS: '/admin/users',
    LIST_KYC: '/admin/kyc',
    GET_KYC_DETAIL: (id: string) => `/admin/kyc/${id}`,
    APPROVE_KYC: (id: string) => `/admin/kyc/${id}/approve`,
    REJECT_KYC: (id: string) => `/admin/kyc/${id}/reject`,
    LIST_VEHICLES: '/admin/vehicles',
    GET_VEHICLE_DETAIL: (id: string) => `/admin/vehicles/${id}`,
    APPROVE_VEHICLE: (id: string) => `/admin/vehicles/${id}/approve`,
    REJECT_VEHICLE: (id: string) => `/admin/vehicles/${id}/reject`,
    LIST_RENTALS: '/admin/rentals',
    GET_RENTAL_DETAIL: (id: string) => `/admin/rentals/${id}`,
    UPDATE_RENTAL_STATUS: (id: string) => `/admin/rentals/${id}/status`,
    STATS: '/admin/stats',
    COMMISSION_SETTINGS: '/admin/commission-settings',
    COMMISSION_PAYMENTS: '/admin/commission-payments',
    COMMISSION_PAYMENT_REVIEW: (id: string) =>
      `/admin/commission-payments/${id}/review`,
    FEE_SETTINGS: '/admin/fee-settings',
    INSURANCE_STATS: '/admin/insurance-stats',
  },
  FEE_SETTINGS: '/fee-settings',
  FILES: {
    UPLOAD: '/files/upload',
    UPLOAD_MULTIPLE: '/files/upload-multiple',
    LIST_MY_FILES: '/files/me',
    DELETE_FILE: '/files/:id',
  },
}

export default API_ENDPOINTS
